version: "3.6"
services:
  database:
    environment:
      POSTGRES_DB: ddev
      POSTGRES_PASSWORD_FILE: /ddev/secrets/postgres-password
    image: ${dockerID}/ddev_db:1.2
    secrets:
    - source: postgres-password
      target: /ddev/secrets/postgres-password
    volumes:
    - postgres-data:/var/lib/postgresql/data
  api:
    image: ${dockerID}/ddev_api:1.2
    secrets:
    - source: postgres-password
      target: /ddev/secrets/postgres_password
    environment:
      SPRING_PROFILES_ACTIVE: postgres
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/utility/healthcheck"]
        interval: 30s
        timeout: 10s
        retries: 3
    ports:
    - "8080:8080"
  ui:
    image: ${dockerID}/ddev_ui:1.2
    ports:
    - "3000:3000"
volumes:
  postgres-data: {}
secrets:
  postgres-password:
    file: devsecrets/postgres_password
