version: "3.6"
services:
  database:
    environment:
      POSTGRES_DB: ddev
      POSTGRES_PASSWORD_FILE: /ddev/secrets/postgres-password
    image: ${dockerID}/ddev_db:1.0
    build:
      context: database
    restart: always
    secrets:
    - source: postgres-password
      target: /ddev/secrets/postgres-password
    volumes:
    - postgres-data:/var/lib/postgresql/data
    networks:
    - back-tier
  api:
    build:
      context: api
    image: ${dockerID}/ddev_api:1.0
    secrets:
    - source: postgres-password
      target: /ddev/secrets/postgres_password
    environment:
      SPRING_PROFILES_ACTIVE: postgres
    networks:
    - back-tier
    - front-tier
  ui:
    build:
      context: ui
    image: ${dockerID}/ddev_ui:1.0
    ports:
    - "3000:3000"
    networks:
    - front-tier
volumes:
  postgres-data: {}
secrets:
  postgres-password:
    file: devsecrets/postgres_password
networks:
  back-tier:
  front-tier:
