version: "3.6"
services:
  database:
    environment:
      POSTGRES_DB: ddev
      POSTGRES_PASSWORD_FILE: /ddev/secrets/postgres-password
    image: ddev-db:1.1
    restart: always
    secrets:
    - source: postgres-password
      target: /ddev/secrets/postgres-password
    volumes:
    - postgres-data:/var/lib/postgresql/data
    networks:
    - back-tier
  api:
    image: ddev-api:1.1
    secrets:
    - source: postgres-password
      target: /ddev/secrets/postgres_password
    environment:
      SPRING_PROFILES_ACTIVE: postgres
    ports:
    - "8080:8080"
    - "5005:5005"
    networks:
    - back-tier
volumes:
  postgres-data: {}
secrets:
  postgres-password:
    file: devsecrets/postgres_password
networks:
  back-tier:
