version: "3.1"

services:
  database:
    image: <Docker ID>/ddev-db:1.0
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB: ddev
    ports:
      - "5432:5432" 
    networks:
      - back-tier
    secrets:
      - postgres_password

  api:
    image: <Docker ID>/ddev-api:1.0
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - front-tier
      - back-tier
    secrets:
      - postgres_password

  ui:
    image: <Docker ID>/ddev-ui:1.0
    ports:
      - "3000:3000"
    networks:
      - front-tier

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password
    
networks:
  front-tier:
  back-tier:
